### ISSUE TITLE
[FLI-507] Ability to whitelist certain users

### ISSUE THREAD

**Issue by JGaudette** [flipt-io/flipt#1872]
### Problem

I am trying to lock down Flipt to just certain users within my google oauth project, rather than everyone who is in the user pool.

### Ideal Solution

Ability to pass Flipt a list of email addresses that are allowed access.  Ideally in either the config, an environment variable, or both.

### Additional Context

We tried to limit this within Google itself but that appears to not be an option from within a project, with the expectation being that the authorization piece is done on the application side.

<sub>[FLI-507](https://linear.app/flipt/issue/FLI-507/ability-to-whitelist-certain-users)</sub>

**Comment by GeorgeMac** [comment]
Thanks @JGaudette ! This came up during the design of the authentication features.
I was under the impression some OIDC providers at-least offered a way to scope who has access to generated OAuth clients. I thought Google for example had the concept of making their clients `internal` or `external`. But I didn't validate the extent of that.

I think we should probably add this capability to Flipt either way, but I will check just incase I can get you unblocked without a code change to Flipt.

This particular feature would be specific to the OIDC authentication method we have for now.
Since it is the only one which currently handles session based and email based authentication.
So I would propose we add it to the OIDC section of the configuration.

What do you think of the following:
```diff
authentication:
  methods:
    oidc:
      enabled: true
+     email_matches:
+           - foo@example.com
+           - ^.*@yourorg.com$
      providers:
        some_provider: # insert your provider name here
          issuer_url: "https://some.oidc.issuer.com"
          client_id: "some_client_identifier"
          client_secret: "some_client_secret_credential"
          redirect_address: "https://your.flipt.instance.url.com"
          scopes:
            - email
            - profile
```

We could support both exact matches and regular expressions.
My thought being it would probably be nice to capture all email address for a given domain.

**Comment by GeorgeMac** [comment]
This is what I was thinking of when I was experimenting with integrating this feature with Google:
https://support.google.com/cloud/answer/10311615#user-type-internal&zippy=%2Cinternal

https://www.flipt.io/docs/guides/login-with-google#1-configure-your-oauth-consent-screen
<img width="767" alt="Screenshot 2023-07-15 at 12 48 15" src="https://github.com/flipt-io/flipt/assets/1253326/67d8b73c-9100-46bf-813a-31085045b69a">

But I will take a moment soon to try make an internal client like this, and confirm that this actually works as expect.

**Comment by allocate-engineering** [comment]
Hi @GeorgeMac,

Thank you for the response!  Yeah that proposal you have for the config update would work perfectly for our use case.  Unfortunately google's `internal` and `external` is only limited to whether logins can happen from outside of our domain versus only internal to it, and you can't individually select users to be able to login under that specific project or not.

Thanks again!  This config update would be awesome!

**Comment by JGaudette** [comment]
Hi @GeorgeMac,

Thank you for the response! Yeah that proposal you have for the config update would work perfectly for our use case. Unfortunately google's internal and external is only limited to whether logins can happen from outside of our domain versus only internal to it, and you can't individually select users to be able to login under that specific project or not.

Thanks again! This config update would be awesome!

**Comment by GeorgeMac** [comment]
Just to re-iterate what was mentioned on Discord:

We're aiming to get this into the next release. We aiming for a release candidate this week (something like `1.24.0-rc1`), but I doubt the feature will be available until we either make a second release candidate or we do the full release of `1.24.0`.

Hopefully though we will have the full release together in the next couple weeks.

**Comment by JGaudette** [comment]
thank you @GeorgeMac, fantastic news!

**Comment by markphelps** [comment]
FYI this will be out in the next release, likely Monday. We can create a release candidate as well if you'd like to try it before then

**Comment by markphelps** [comment]
Added in the latest release https://github.com/flipt-io/flipt/releases/tag/v1.24.0

Thank you for the suggestion!
