### ISSUE TITLE
Flipt CMD ignores --create-namespace flag

### ISSUE THREAD

**Issue by Farbauti89** [flipt-io/flipt#2070]
### Describe the Bug

I tried to import a configuration for a non existing namespace into my Flipt server, by using the commandline tool with the `--create-namespace` flag. Instead of creating the new namespace, I get the following error:

    FATAL   execute {"error": "namespace \"test\" not found"}

### Version Info

Version: v1.24.2
Commit: 3f2135b7385ffb041ca7f858cfff734046cf69f6
Build Date: 2023-08-07T15:55:04Z
Go Version: go1.20.7

### To Reproduce

* create a configuration file "test.yaml" to import
* run `./flipt import ./test.yaml --create-namespace`

####  content of test.yaml
version: "1.1"
namespace: test
flags:
  - key: test_flag
    name: TEST_FLAG
    type: BOOLEAN_FLAG_TYPE
    description: A test flag
    enabled: true
    rollouts:
      - threshold:
          percentage: 100
          value: true

### Expected Behavior

The namespace is created and the configuration is imported.

**Comment by yquansah** [comment]
Hello 👋  @Farbauti89 Apologies for the confusion, and if this wasn't documented well. But along with the `--create-namespace` flag. You will also have to provide a `--namespace {NAMESPACE_NAME}` flag as well. So in your case the command would look like:

```bash
$ ./flipt import ./test.yml --namespace test --create-namespace 
```

**Comment by Farbauti89** [comment]
Hi @yquansah, thanks for your reply.
Sadly, this leads to the exact same error.

    $ ./flipt import ./test.yaml --namespace test --create-namespace 
    2023-09-04T05:43:44.397Z        DEBUG   flipt/import.go:98      importing       {"source_path": "./test.yaml"}
    Error: namespace "test" not found
    ...
    2023-09-04T05:43:44Z    FATAL   execute {"error": "namespace \"test\" not found"}

**Comment by GeorgeMac** [comment]
Intruiging... 🤔 Will try and repro

**Comment by GeorgeMac** [comment]
I think I see the bug. The importer code is expecting a gRPC not found error code and assuming it is using a client to talk to Flipt. In this instance, the importer is being run directly against the DB. So the error is going to be a not found error from the storage layer:
https://github.com/flipt-io/flipt/blob/ad1ed218e2d17d4b1230f8c1f2beb08b385457ad/internal/ext/importer.go#L106-L108

To confirm this, if you run the import with `--address` pointed at your running instance of Flipt, instead of directly against a DB, it should work as expected. In the meantime, I can work on a fix.

**Comment by GeorgeMac** [comment]
I opened a PR with a failing test in it. Going to work on the fix now ☝️

**Comment by GeorgeMac** [comment]
I think the PR is ready now. Should be able to get this fixed in a patch release.
