### ISSUE TITLE
[FLI-665] [Feature Request] Namespace scoped static tokens

### ISSUE THREAD

**Issue by jarviliam** [flipt-io/flipt#2287]
### Problem

We can utilize namespaces to group flags for different teams/environments but if one were to generate static tokens for each team's applications to be used in a centralized flipt deployment there's no way to prevent tokens generated for a team's namespace from accessing other namespaces.

### Ideal Solution

When generating a static token we can select which namespaces the token allows access to.
By default a token can interact with all namespaces.

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

Thanks for the work on flipt!

<sub>[FLI-665](https://linear.app/flipt/issue/FLI-665/[feature-request]-namespace-scoped-static-tokens)</sub>

**Comment by markphelps** [comment]
This is pretty crazy haha because I literally asked the team this same question in our internal slack earlier this afternoon!! It must be meant to be!

![CleanShot 2023-10-25 at 21 55 17@2x](https://github.com/flipt-io/flipt/assets/209477/bc78f733-c13b-4760-ade8-805f456833fa)

Very validating that its a feature that users would find useful. Will def try to come up with a way to make this happen. 

Question: would you want to be able to scope a token to a single namespace or multiple namespaces?

**Comment by 0xskynet** [comment]
+1 was playing with flipt and setting up tokens. Was wondering same if there is any way to create namespace specific tokens. Would be great.

**Comment by markphelps** [comment]
Thanks @0xskynet ! Would you want to scope to a single namespace or multiple?

**Comment by 0xskynet** [comment]
I would scope to a single namespace, as it would be simple and intuitive than multiple namespaces.

**Comment by jarviliam** [comment]
Yeah I have the same opinion. If I'm splitting namespaces by teams & environments I can only see myself needing single namespace scoped tokens!

**Comment by markphelps** [comment]
Thank you both! Makes implementation simpler that way from a UI perspective too. Will get this prioritized!

**Comment by markphelps** [comment]
WIP PR here: https://github.com/flipt-io/flipt/pull/2352

lmk if you have any feedback
