### ISSUE TITLE
[Bug]:  Boolean Flags never return reason "FLAG_DISABLED_EVALUATION_REASON", and `enable` not working

### ISSUE THREAD

**Issue by Tai-ch0802** [flipt-io/flipt#2700]
### Bug Description

I tried to use `Boolean Flag` and disable it, but not get the reson `FLAG_DISABLED_EVALUATION_REASON`.
When I change to disable, the boolean flag only change the value of  `Default Rollout`.
<img width="1102" alt="image" src="https://github.com/flipt-io/flipt/assets/8073199/b260fd50-7dfc-4eb4-b89f-257e5d5f8c31">

it will cause "Even the boolean flag is disable, my first `Segment Rollout` still work". 
```
# request
curl --location 'http://example.flipt/evaluate/v1/boolean' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data '{
  "context": {
    "memberid": "qweqwe",
    "active": "true"
  },
  "entityId": "qweqwe",
  "flagKey": "feature-day2",
  "namespaceKey": "ap123-sit"
}'

# response
{
    "enabled": true,
    "reason": "MATCH_EVALUATION_REASON",
    "requestId": "2f78e286-69c5-460a-a835-476071d8cabf",
    "requestDurationMillis": 4.317299,
    "timestamp": "2024-01-23T09:19:32.921679421Z",
    "flagKey": "feature-day2"
}

```

But I think the `response.enable` should be false, and response.reason should be "FLAG_DISABLED_EVALUATION_REASON". 
```
# expected response
{
    "enabled": false,
    "reason": "FLAG_DISABLED_EVALUATION_REASON",
    "requestId": "2f78e286-69c5-460a-a835-476071d8cabf",
    "requestDurationMillis": 4.317299,
    "timestamp": "2024-01-23T09:19:32.921679421Z",
    "flagKey": "feature-day2"
}

```

### Version Info

```
 
    _________       __
   / ____/ (_)___  / /_
  / /_  / / / __ \/ __/
 / __/ / / / /_/ / /_
/_/   /_/_/ .___/\__/
         /_/

 Version: v1.35.0
 Commit: 4b9174bf4b9eb184b6377a5307633f5110700695
 Build Date: 2024-01-09T15:58:12Z
 Go Version: go1.21.5
 OS/Arch: linux/amd64
```

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. create Boolean flag

2. create segment `all-user` (Match type: all, Constraints: ref the image)
<img width="1098" alt="image" src="https://github.com/flipt-io/flipt/assets/8073199/549689f2-4ec9-4c67-a9e1-5fd328aa8270">
 
3. attach Rollouts, segment
<img width="1092" alt="image" src="https://github.com/flipt-io/flipt/assets/8073199/cfa447c9-a2d2-4a0d-9e32-682739d87cf5">

4. call api `/evaluate/v1/boolean`
5. change Boolean flag to disable, and default rollout change to `false`
<img width="1092" alt="image" src="https://github.com/flipt-io/flipt/assets/8073199/30d6fe1b-450e-4134-ab10-4d65057634c5">

6. call api `/evaluate/v1/boolean`

### Expected Behavior

it will cause "Even the boolean flag is disable, my first `Segment Rollout` still work". 
I think the `response.enable` should be false, and response.reason should be "FLAG_DISABLED_EVALUATION_REASON".

```
# expected response
{
    "enabled": false,
    "reason": "FLAG_DISABLED_EVALUATION_REASON",
    "requestId": "2f78e286-69c5-460a-a835-476071d8cabf",
    "requestDurationMillis": 4.317299,
    "timestamp": "2024-01-23T09:19:32.921679421Z",
    "flagKey": "feature-day2"
}

```

### Additional Context

config: same as init (flipt config init)
database: SQL Lite

**Comment by erka** [comment]
@Tai-ch0802 thank you for report. It works for variant flag type, but is broken for boolean flag type. We will fix it shortly.

@markphelps is it any chance to include the fix into v1.36?

**Comment by GeorgeMac** [comment]
Sorry @erka and @Tai-ch0802 this is actually behaving as expected.

With boolean flags, evaluation happens serially over the rollouts until a condition is true.
If it is true, then it returns the value associated with the matching rollout.

The enabled property on a boolean flag is the last condition of the set of rules and is what everything defaults to when other conditions do not match. In this situation, the flag is behaving as expected, because it matched the segment and returned the Value associated with the rollout.

**Comment by GeorgeMac** [comment]
The flag demonstrated above can be broken down into this sequence of conditions:
- if matches segment `all-users` return `true`
- else return default, which is `false` (where default is the `enabled` base property on the flag)

**Comment by GeorgeMac** [comment]
The flag disabled reason predates boolean type flags. It came from the variant type flag, when we only had one type of flag.
We could re-introduce it when the returned value is false I suppose.

But it had more intentional meaning for the variant type flag, which could be enabled / disabled in its entirety. There was no match on segments, because the flag was hard disabled. Where a boolean type flag is more of a value (true or false) which you're trying to resolve based on some context. Like some remote boolean variable.

**Comment by GeorgeMac** [comment]
@erka that is a fair expectation based on our current listing page. Perhaps we can come up with some better way to visualize boolean flags in the list view. One thing might to make it clear that is `default: disabled` and that there are e.g. `n` conditions which could change that.

**Comment by Tai-ch0802** [comment]
.@GeorgeMac @erka  thank you both.

@GeorgeMac You mentioned one important thing, HARD KILL SWITCH.
I think there are two different things, both important.

- hard kill switch
- policy in 'default deny all' or 'default accept all'

Is there any possibility of handling these? 
Maybe there is another property to control the policy of default value.
The existing property 'enable' for the hard kill switch.

If 'hard kill switch' exists in the boolean flag eather, there will be more useful and intuitive.

**Comment by GeorgeMac** [comment]
In case of emergency there are few ways to handle the change flag to always return `true` or always return `false`.

One way is to just remove all the rollouts. The rollouts are the things which can short-circuit the flag and change the value from the default. This is perhaps a little more tenable with e.g. the `git` backend, because you have Git history and version control, which you can restore and revert once you want to get back to the state you were in before. In you want to not loose track of how the flag was configured before removing rollouts.

A second way is to change the _value_ on each rollout to be the same as the default. This has the same effect, but leaves the definitions intact if you want don't want to loose them. So you can just change the values back when you want to start progressively enabling it again.

A third way is to just add a threshold or segment rule that always matches every request and have it return either `true` or `false`. For example, percentage == 100% or matching a segment with 0 constraints. This will short-circuit to always return the `value` on that rollout.

I think we definitely could do better explaining this in the documentation. I wonder too whether there are just some things we could do in the UI to make this clearer. Just trying to see if there is a way to not incur a breaking change and working with the existing data model, as we're strongly committed to preserve backwards compatibility.

**Comment by Tai-ch0802** [comment]
I got it. Thank you for suggestions.
I'll close this bug issue.

> In case of emergency there are few ways to handle changing flag to always return `true` or always return `false`.
> 
> One way is to just remove all the rollouts. The rollouts are the things which can short-circuit the flag and change the value from the default. This is perhaps a little more tenable with e.g. the `git` backend, because you have Git history and version control, which you can restore and revert once you want to get back to the state you were in before. In you want to not loose track of how the flag was configured before removing rollouts.
> 
> A second way is to change the _value_ on each rollout to be the same as the default. This has the same effect, but leaves the definitions intact if you don't want to loose them. So you can just change the values back when you want to start progressively enabling it again.
> 
> A third way is to just add a threshold or segment rule that always matches every request and have it return either `true` or `false` as the first rollout rule. For example, percentage == 100% or matching a segment with 0 constraints. This will short-circuit to always return the `value` on that first rollout.
> 
> I think we definitely could do better explaining this in the documentation. I wonder too whether there are just some things we could do in the UI to make this clearer. Just trying to see if there is a way to not incur a breaking change and working with the existing data model, as we're strongly committed to preserve backwards compatibility.

**Comment by GeorgeMac** [comment]
Thanks for raising this @Tai-ch0802 🙏 I think there is definitely something here we can improve.
You're not the first person to find this confusing and it was much a topic of discussion when designing the boolean flag in this way.
