### ISSUE TITLE
Running Flipt UI under different path then root

### ISSUE THREAD

**Issue by martin-gft** [flipt-io/flipt#2723]
### Problem

Running the Flipt UI under a different path than root (e.g. http://example.com/flipt using a reverse proxy) will result in the assets of the frontend not loading. I guess the REST calls to the API will also run into the same problem.

![image](https://github.com/flipt-io/flipt/assets/116256619/4fa8f03c-8bcb-45eb-8e15-1f658f50831e)

### Ideal Solution

Adding a new configuration option in the server section called server.basepath or server.relativepath.
Default still is / but can be overwritten by any subdirectiory like /flipt.

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by GeorgeMac** [comment]
As gross as it sounds, a `strings.ReplaceAll` on the static assets, given some prefix is provided to Flipt, and then if we cache that... might work. Sounds hideous, but because we statically generate all these assets at build time and don't currently have a way to e.g. template them in at runtime from Go to the bundled JS project... Might be all we can do.

Someone out there might have a better trick though.
