### ISSUE TITLE
[FLI-938] Allow passing a starting dir `flipt validate` 

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2916]
### Problem

Currently, the [validate](https://www.flipt.io/docs/cli/commands/validate) cli command always scans from the current directory, looking for `features.yml` / `.flipt.yml` files

### Ideal Solution

It would be nice if we could take in an optional path (ie:`flipt validate /tmp`) to use as starting point so that you first don't have to `cd` into the target directory before running `flipt validate`

### Search

- [X] I searched for other open and closed issues before opening this

<sub>[FLI-938](https://linear.app/flipt/issue/FLI-938/allow-passing-a-starting-dir-flipt-validate)</sub>

**Comment by erka** [comment]
Currently `flipt validate` allows to specify the files relatively currently directory.  You could run it like `flipt validate production.yml extra/feature.yml`.

https://github.com/flipt-io/flipt/blob/cc9c0eca466c08e7517a58428509999fbe9204c1/cmd/flipt/validate.go#L71-L75

There is no documentation about this use case. @GeorgeMac could you please bring some light on it?

**Comment by GeorgeMac** [comment]
@erka When `flipt validate` was initially implemented it only supported taking explicit paths in this way.
This was back when it was a prototype for the GitHub action.
We quickly updated it to make the zero argument form index aware, so that it was inline with how the backends worked, but still backwards compatible. So that `flipt validate` was a simple catch all, that worked exactly how running git or local over the same directory does.

You're right we don't have the old form (explicit paths) document here https://www.flipt.io/docs/cli/commands/validate#behavior on in the CLI help text.

My suggestion here would be to add a flag `--workdir` or `-w` instead for this behaviour.

**Comment by erka** [comment]
@markphelps are you fine with George's suggestion?
