### ISSUE TITLE
Connect to multiple PostgreSQL hosts

### ISSUE THREAD

**Issue by Gogoloogu** [flipt-io/flipt#2982]
### Problem

When trying to specify multiple `hosts` in the connection URL or in the host property, flipt fails to start with an error:
`Error: getting db driver for: postgres: dial tcp: lookup HOST1:5432,HOST2: no such host`

### Ideal Solution

It is possible to specify multiple postgresql hosts in the connection URL, as well as special parameters that are available in libpq. For example `target_session_attrs`.

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

I'm trying to specify this DB configuration:
```
db:
  url: postgresql://user:password@HOST1:5432,HOST2:5432/flipt-db?target_session_attrs=primary&application_name=flipt
```

**Comment by markphelps** [comment]
Hey @Gogoloogu thanks for the request!

I think we'll need to switch Postgres DB libraries from our current [lib/pq](https://github.com/lib/pq) to something like [pgx](https://github.com/jackc/pgx) in order to support this as it looks like [lib/pq cannot handle multiple hosts](https://github.com/lib/pq/issues/683) and also looks like its in [maintenance mode](https://github.com/lib/pq?tab=readme-ov-file#status) (so it might be time to switch anyways to another impl)

Looks like [hashicorp/vault]() ran into the [same thing and decided to switch](https://github.com/hashicorp/vault/issues/7247) to pgx

We'll have to do some investigation to see:

1. how difficult a lift this would be to switch (Im hoping not too difficult since we don't do anything crazy as far as queries)
2. how this will affect performance (hopefully it will be an improvement)

So this might take a little bit of time, but I think its doable and likely the right move to switch to a better maintained library like pgx anyways.

It looks like the dburl library that we use to parse db connection strings [natively only supports `lib/pq`](https://github.com/xo/dburl?tab=readme-ov-file#database-schemes-aliases-and-drivers), however they do allow us to add our own schema to driver support, so that might be possible to get it to support pgx.

[golang migrate](https://github.com/golang-migrate/migrate/tree/master/database/pgx/v5) which we use for migrations also seems to support pgx.. so we should be good there

But yeah I think this is doable, it just might take a bit of work/time but any help would be appreciated!!
